### ISSUE TITLE
Issues using the lib

### ISSUE THREAD

**Issue by svb688** [martinRenou/pybind_json#3]
I'm having a tough time using this lib. I've copied pybind_json.hpp into my include dir as I don't have access to conda. 

Then my main file is:

````
#include <pybind_json.hpp>

int main()
{
    nlohmann::json j;
    j["a"] = 1;
    j["b"] = 2;

    py::dict d;
    d["a"] = 1;
    d["b"] = 2;

    py::dict d2 = j;
    nlohmann::json j2 = d;
}
````

The last two lines give compilation errors of:
"no suitable user-defined conversion from "nlohmann::json" to "pybind11::dict" exists"
"no suitable user-defined conversion from "pybind11::dict" to "nlohmann::json" exists"

respectively. So I am unable to do any conversion. I must be missing something simple. I am able to compile the code with the last 2 lines commented out so I know the nlohmann and pybind11 libs are properly being used.

**Comment by svb688** [comment]
Casting py::dict as an object works (which makes sense), but I am trying to repeat the example. Should I just be casting or change the serializer return type?

**Comment by martinRenou** [comment]
Thanks for the report, it is possible that the README example does not compile... I don't recall testing it. I guess you can change the serializer return type if you want.

**Comment by martinRenou** [comment]
Maybe we should add overloads to the serializer that would do the casting automatically.

Also you can write your code this way (this is how it's written in tests):
```cpp
py::object obj = py::dict("number"_a=1234, "hello"_a="world");
nl::json j = obj;
```

**Comment by martinRenou** [comment]
I fixed the README example, thanks again for reporting :)
